disabled_rules:
  - identifier_name
  - todo
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_try
  - line_length
  - large_tuple
included:
  - Sources
  - Tests
